options:
    packURL: "https://github.com/fitfamforever1/apocalpticrpg/releases/download/resourcepack/latest.zip"
    packHash: "9d4480f79fd574c537497cb8e8fa4d95f3d2a25c"


on join:
    wait 2 seconds
    if {pack.bypass::%player%} is true:
        stop trigger
    send the resource pack from URL {@packURL} with hash {@packHash} to player


command /resend:
    trigger:
        send the resource pack from URL {@packURL} with hash {@packHash} to player
        send "&8[<##91AAFF>ᴘᴀᴄᴋ&8] &aʀᴇꜱᴇɴᴅɪɴɢ ʀᴇꜱᴏᴜʀᴄᴇ ᴘᴀᴄᴋ..." to player

command /packlink:
    trigger:
        send formatted "&8[<##91AAFF>ᴘᴀᴄᴋ&8] <click:open_url:'https://cdn.discordapp.com/attachments/1524137184427249920/1526251825874079764/latest.zip?ex=6a565847&is=6a5506c7&hm=eb3e7877267aa1e8696b3dab83ce819bbc86dc9d6ee102087573a532b64f3bab&'><yellow>ᴘᴀᴄᴋ ʟɪɴᴋ</yellow></click>" to player
        send "&8[<##91AAFF>ᴘᴀᴄᴋ&8] ʏᴏᴜ ᴄᴀɴ ᴜꜱᴇ /ᴘᴀᴄᴋɪɢɴᴏʀᴇ ᴛᴏ ᴀᴠᴏɪᴅ ʀᴇꜱᴏᴜʀᴄᴇᴘᴀᴄᴋ." to player

command /packignore:
    trigger:
        if {pack.bypass::%player%} is true:
            set {pack.bypass::%player%} to false
            send "&8[<##91AAFF>ᴘᴀᴄᴋ&8] &eʏᴏᴜ ᴡɪʟʟ ɴᴏᴡ ʙᴇ &cʀᴇǫᴜɪʀᴇᴅ&e ᴛᴏ ᴀᴄᴄᴇᴘᴛ ᴛʜᴇ ʀᴇꜱᴏᴜʀᴄᴇ ᴘᴀᴄᴋ." to player
        else:
            set {pack.bypass::%player%} to true
            send "&8[<##91AAFF>ᴘᴀᴄᴋ&8] &eʏᴏᴜ ᴄᴀɴ ɴᴏᴡ &aɪɢɴᴏʀᴇ&e ᴛʜᴇ ʀᴇꜱᴏᴜʀᴄᴇ ᴘᴀᴄᴋ ʀᴇǫᴜɪʀᴇᴍᴇɴᴛ." to player


command /packsend <player>:
    permission: pack
    permission message: &cYou don't have permission to do that.
    trigger:
        send the resource pack from URL {@packURL} with hash {@packHash} to arg-1
        send "&8[<##91AAFF>ᴘᴀᴄᴋ&8] &aꜱᴇɴᴛ ᴛʜᴇ ʀᴇꜱᴏᴜʀᴄᴇ ᴘᴀᴄᴋ ᴛᴏ %arg-1%." to player


command /packsendall:
    permission: pack
    permission message: &cYou don't have permission to do that.
    trigger:
        loop all players:
            if {pack.bypass::%loop-player%} is true:
                continue
            send the resource pack from URL {@packURL} with hash {@packHash} to loop-player
        send "&8[<##91AAFF>ᴘᴀᴄᴋ&8] &aꜱᴇɴᴛ ᴛʜᴇ ʀᴇꜱᴏᴜʀᴄᴇ ᴘᴀᴄᴋ ᴛᴏ ᴇᴠᴇʀʏᴏɴᴇ ᴏɴʟɪɴᴇ." to player


on resource pack request response:
    if resource pack is successfully installed:
        send action bar "&8[<##91AAFF>ᴘᴀᴄᴋ&8] &aʀᴇꜱᴏᴜʀᴄᴇ ᴘᴀᴄᴋ ʟᴏᴀᴅᴇᴅ!" to player
        stop trigger

    if {pack.bypass::%player%} is true:
        stop trigger

    if resource pack is declined:
        send "&8[<##91AAFF>ᴘᴀᴄᴋ&8] &cʀᴇꜱᴏᴜʀᴄᴇᴘᴀᴄᴋ ɪꜱ ᴀ ᴍᴜꜱᴛ ᴡʜɪʟᴇ ᴘʟᴀʏɪɴɢ ᴛʜᴇ ꜱᴇʀᴠᴇʀ, ᴅᴏᴡɴʟᴏᴀᴅ ɪᴛ ꜰʀᴏᴍ /ᴘᴀᴄᴋʟɪɴᴋ ᴏʀ ᴅᴏ /ʀᴇꜱᴇɴᴅ." to player
        stop trigger

    if resource pack is failed to download:
        send action bar "&8[<##91AAFF>ᴘᴀᴄᴋ&8] &cꜰᴀɪʟᴇᴅ ᴛᴏ ᴅᴏᴡɴʟᴏᴀᴅ ᴛʜᴇ ʀᴇꜱᴏᴜʀᴄᴇ ᴘᴀᴄᴋ, ᴀᴛᴛᴇᴍᴘᴛɪɴɢ ʀᴇꜱᴇɴᴅ..." to player
        wait 1 second
        send the resource pack from URL {@packURL} with hash {@packHash} to player