on right click with stick:
    if name of player's tool is not "&fArcane Wand":
        stop

    set {_uuid} to uuid of player

    if {cooldown_arcane::%{_uuid}%} is set:
        if {cooldown_arcane::%{_uuid}%} > now:
            stop

    if {mana::%{_uuid}%} is not set:
        set {mana::%{_uuid}%} to 0

    if {mana::%{_uuid}%} < 20:
        send action bar "&cNot enough mana." to player
        stop

    set {cooldown_arcane::%{_uuid}%} to now + 0.5 seconds

    remove 20 from {mana::%{_uuid}%}
    clampMana(player)
    saveMana(player)

    spawn a snowball at player's eye location
    set {_ball} to last spawned entity
    set {_dir} to vector from yaw player's yaw and pitch player's pitch
    set velocity of {_ball} to {_dir} * 5
    set {magicbullet_shooter::%uuid of {_ball}%} to uuid of player
    send action bar "&fMagic Bullet fired! &b-20 Mana" to player

on projectile hit:
    projectile is a snowball
    {magicbullet_shooter::%uuid of projectile%} is set

    cancel event
    set {_source} to damage source from magic
    damage victim by 14 with {_source}
    delete {magicbullet_shooter::%uuid of projectile%}