on damage:
    damage cause is projectile
    projectile is an arrow
    attacker is a player
    set {_bow} to attacker's tool
    if display name of {_bow} is "&fThunderpriece Bow":
        cancel event
        delete projectile
        set {_entity} to victim
        set {_source} to damage source from arrow
        damage {_entity} by 7.5 with {_source}
        strike lightning at location of {_entity}
        if {_entity} is a player:
            send action bar "&8⚡ &fYou have been &7smited&f!" to {_entity}