function getModelId(itemId: number) :: number:
    if {itemId} <= 10:
        return 1
    else if {itemId} <= 20:
        return 2
    else if {itemId} <= 30:
        return 3
    else if {itemId} <= 40:
        return 4
    else:
        return 5

function setSlot(player: player, slotIndex: number, abilityId: number):
    set {_prefix} to slotIndex - 7
    set {_model_id} to getModelId({abilityId})

    set {_item} to air
    set item model of {_item} to "icon/%{_prefix}%%{_model_id}%"
    set {player}'s inventory slot {slotIndex} to {_item}

command /setslots <number> <number>:
    trigger:
        setSlot(player, arg-1, arg-2)