function getModelId(itemId: number) :: number:
    if {itemId} <= 10:
        return 1
    else if {itemId} <= 20:
        return 2
    else if {itemId} <= 30:
        return 3
    else if {itemId} <= 40:
        return 4
    else:
        return 5

command /slot8 <number>:
    trigger:
        set {_ability_id} to arg-1
        set {_model_id} to getModelId({_ability_id})

        set {_item} to air
        set item model of {_item} to "icon/1%{_model_id}%"
        set player's inventory slot 8 to {_item}

        send "&aSet slot 8 item model to: %{_model_id}% (ability %{_ability_id}%)"

command /slot9 <number>:
    trigger:
        set {_ability_id} to arg-1
        set {_model_id} to getModelId({_ability_id})

        set {_item} to air
        set item model of {_item} to "icon/2%{_model_id}%"
        set player's inventory slot 9 to {_item}

        send "&aSet slot 9 item model to: %{_model_id}% (ability %{_ability_id}%)"