on load:
    load yaml "plugins/Skript/yaml/blocked_words.yml" as "blocked"
    set {blocked_words::*} to yaml list "blocked_words" from "blocked"
    loop {blocked_words::*}:

on chat:
    cancel event
    set {_check} to the placeholder "betterteams_inTeam" from player
    set {_prefix} to ""
    if {_check} is "true":
        set {_name} to the placeholder "betterteams_name" from player
        set {_color} to the placeholder "betterteams_color" from player
        set {_name} to SmallCaps("%{_name}%")
        set {_prefix} to "&8[%{_color}%%{_name}%&8] "
    
    set {_msg} to message
    set {_lower} to message in lowercase
    
    loop {blocked_words::*}:
        set {_word} to loop-value
        if {_lower} contains {_word}:
            set {_length} to length of {_word}
            set {_first} to first character of {_word}
            set {_last} to last character of {_word}
            
            set {_censor} to "%{_first}%"
            loop ({_length} - 2) times:
                set {_censor} to "%{_censor}%*"
            set {_censor} to "%{_censor}%%{_last}%"
            
            regex replace "(?i)%{_word}%" in {_msg} with {_censor}
    
    broadcast "%{_prefix}%&7%player%&8: &f%{_msg}%"