command /saveitem <text>:
    permission: admin.save
    usage: /saveitem <id>
    trigger:
        if player's tool is air:
            send "&cYou're not holding anything!" to player
            stop
        set {item::%arg-1%} to player's tool
        send "&aSaved item as &e%arg-1%" to player

command /giveitem <text>:
    permission: admin.save
    usage: /giveitem <id>
    trigger:
        if {item::%arg-1%} is set:
            give {item::%arg-1%} to player
            send "&aGave you item &e%arg-1%" to player
        else:
            send "&cNo item found with id &e%arg-1%" to player
            
function getRarityLine(rarity: text) :: text:
    if {_rarity} is "special":
        return "&cꜱᴘᴇᴄɪᴀʟ"
    if {_rarity} is "divine":
        return "&bᴅɪᴠɪɴᴇ"
    if {_rarity} is "mythic":
        return "&dᴍʏᴛʜɪᴄᴀʟ"
    if {_rarity} is "legendary":
        return "&6ʟᴇɢᴇɴᴅᴀʀʏ"
    if {_rarity} is "epic":
        return "&5ᴇᴘɪᴄ"
    if {_rarity} is "rare":
        return "&9ʀᴀʀᴇ"
    if {_rarity} is "uncommon":
        return "&aᴜɴᴄᴏᴍᴍᴏɴ"
    if {_rarity} is "common":
        return "&fᴄᴏᴍᴍᴏɴ"
    return ""
    

function sword(item: item, rarity: text, level: number):: item:
    set {_damage} to round(5 + ({_level} * 1.8))
    set {_attackspeed} to 1.6
    set {_critchance} to round(8 + ({_level} * 0.5))
    set {_critdamage} to round(50 + ({_level} * 2))
    set {_dps} to round({_damage} * {_attackspeed}, 1)
    
    set {_rarityline} to getRarityLine({_rarity})
    
    set line 1 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ɪɴғᴏ"
    set line 2 of lore of {_item} to "&8┃ &7ᴛʏᴘᴇ &8» &eꜱᴡᴏʀᴅ"
    set line 3 of lore of {_item} to "&8┃ &7ʀᴀʀɪᴛʏ &8» %{_rarityline}%"
    set line 4 of lore of {_item} to ""
    set line 5 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ꜱᴛᴀᴛꜱ"
    set line 6 of lore of {_item} to "&8┃ &7ᴅᴘꜱ &8» &c+%{_dps}%"
    set line 7 of lore of {_item} to "&8┃ &7ᴄʀɪᴛ ᴄʜᴀɴᴄᴇ &8» &9+%{_critchance}%%%"
    set line 8 of lore of {_item} to "&8┃ &7ᴄʀɪᴛ ᴅᴀᴍᴀɢᴇ &8» &9+%{_critdamage}%%%"

    set {_item} to unbreakable {_item}
    set item flags of {_item} to all item flags
  
    apply attribute modifier to {_item}:
        id: "minecraft:base_attack_speed"
        attribute: attack speed
        amount: -2.4
        slot: mainhand_slot_group
        operation: add_number  
  
    set text data tag "itemstat:type" of {_item} to "sword"
    set number data tag "itemstat:damage" of {_item} to {_damage}
    set number data tag "itemstat:crit_chance" of {_item} to {_critchance}
    set number data tag "itemstat:crit_damage" of {_item} to {_critdamage}
   
    return {_item}
    
function dagger(item: item, rarity: text, level: number):: item:
    set {_damage} to round(3.5 + ({_level} * 1.45))
    set {_attackspeed} to 2.0
    set {_critchance} to round(12 + ({_level} * 0.6))
    set {_critdamage} to round(45 + ({_level} * 1.5))
    set {_dps} to round({_damage} * {_attackspeed}, 1)
    
    set {_rarityline} to getRarityLine({_rarity})
    
    set line 1 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ɪɴғᴏ"
    set line 2 of lore of {_item} to "&8┃ &7ᴛʏᴘᴇ &8» &eᴅᴀɢɢᴇʀ"
    set line 3 of lore of {_item} to "&8┃ &7ʀᴀʀɪᴛʏ &8» %{_rarityline}%"
    set line 4 of lore of {_item} to ""
    set line 5 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ꜱᴛᴀᴛꜱ"
    set line 6 of lore of {_item} to "&8┃ &7ᴅᴘꜱ &8» &c+%{_dps}%"
    set line 7 of lore of {_item} to "&8┃ &7ᴄʀɪᴛ ᴄʜᴀɴᴄᴇ &8» &9+%{_critchance}%%%"
    set line 8 of lore of {_item} to "&8┃ &7ᴄʀɪᴛ ᴅᴀᴍᴀɢᴇ &8» &9+%{_critdamage}%%%"

    set {_item} to unbreakable {_item}
    set item flags of {_item} to all item flags
  
    apply attribute modifier to {_item}:
        id: "minecraft:base_attack_speed"
        attribute: attack speed
        amount: -2.0
        slot: mainhand_slot_group
        operation: add_number  
  
    set text data tag "itemstat:type" of {_item} to "sword"
    set number data tag "itemstat:damage" of {_item} to {_damage}
    set number data tag "itemstat:crit_chance" of {_item} to {_critchance}
    set number data tag "itemstat:crit_damage" of {_item} to {_critdamage}
   
    return {_item}
    
function axe(item: item, rarity: text, level: number):: item:
    set {_damage} to round(7 + ({_level} * 3.0))
    set {_attackspeed} to 1.0
    set {_critchance} to round(5 + ({_level} * 0.35))
    set {_critdamage} to round(65 + ({_level} * 2.5))
    set {_dps} to round({_damage} * {_attackspeed}, 1)
    
    set {_rarityline} to getRarityLine({_rarity})
    
    set line 1 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ɪɴғᴏ"
    set line 2 of lore of {_item} to "&8┃ &7ᴛʏᴘᴇ &8» &eᴀxᴇ"
    set line 3 of lore of {_item} to "&8┃ &7ʀᴀʀɪᴛʏ &8» %{_rarityline}%"
    set line 4 of lore of {_item} to ""
    set line 5 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ꜱᴛᴀᴛꜱ"
    set line 6 of lore of {_item} to "&8┃ &7ᴅᴘꜱ &8» &c+%{_dps}%"
    set line 7 of lore of {_item} to "&8┃ &7ᴄʀɪᴛ ᴄʜᴀɴᴄᴇ &8» &9+%{_critchance}%%%"
    set line 8 of lore of {_item} to "&8┃ &7ᴄʀɪᴛ ᴅᴀᴍᴀɢᴇ &8» &9+%{_critdamage}%%%"

    set {_item} to unbreakable {_item}
    set item flags of {_item} to all item flags
  
    apply attribute modifier to {_item}:
        id: "minecraft:base_attack_speed"
        attribute: attack speed
        amount: -3.0
        slot: mainhand_slot_group
        operation: add_number  
  
    set text data tag "itemstat:type" of {_item} to "sword"
    set number data tag "itemstat:damage" of {_item} to {_damage}
    set number data tag "itemstat:crit_chance" of {_item} to {_critchance}
    set number data tag "itemstat:crit_damage" of {_item} to {_critdamage}
   
    return {_item}
    
command /modifysword <text> <number>:
    permission: admin.item
    trigger:
        give player sword(honeycomb, arg-1, arg-2)

command /modifyaxe <text> <number>:
    permission: admin.item
    trigger:
        give player axe(honeycomb, arg-1, arg-2)

command /modifydagger <text> <number>:
    permission: admin.item
    trigger:
        give player dagger(honeycomb, arg-1, arg-2)
        
function helmet(item: item, rarity: text, level: number):: item:
    set {_health} to round((8 + ({_level} * 1.5)) * 1.15)
    set {_defense} to round(8 + ({_level} * 1.2))
    
    set {_rarityline} to getRarityLine({_rarity})

    set line 1 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ɪɴғᴏ"
    set line 2 of lore of {_item} to "&8┃ &7ᴛʏᴘᴇ &8» &eʜᴇʟᴍᴇᴛ"
    set line 3 of lore of {_item} to "&8┃ &7ʀᴀʀɪᴛʏ &8» %{_rarityline}%"
    set line 4 of lore of {_item} to ""
    set line 5 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ꜱᴛᴀᴛꜱ"
    set line 6 of lore of {_item} to "&8┃ &7ʜᴇᴀʟᴛʜ &8» &c+%{_health}%"
    set line 7 of lore of {_item} to "&8┃ &7ᴅᴇғᴇɴꜱᴇ &8» &a+%{_defense}%"
    
    set {_item} to unbreakable {_item}
    set item flags of {_item} to all item flags
    
    set text data tag "itemstat:type" of {_item} to "helmet"
    set number data tag "itemstat:health" of {_item} to {_health}
    set number data tag "itemstat:defense" of {_item} to {_defense}
    
    return {_item}
        
function chestplate(item: item, rarity: text, level: number):: item:
    set {_health} to round((8 + ({_level} * 1.5)) * 1.15)
    set {_defense} to round(8 + ({_level} * 1.2))
    
    set {_rarityline} to getRarityLine({_rarity})

    set line 1 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ɪɴғᴏ"
    set line 2 of lore of {_item} to "&8┃ &7ᴛʏᴘᴇ &8» &eᴄʜᴇꜱᴛᴘʟᴀᴛᴇ"
    set line 3 of lore of {_item} to "&8┃ &7ʀᴀʀɪᴛʏ &8» %{_rarityline}%"
    set line 4 of lore of {_item} to ""
    set line 5 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ꜱᴛᴀᴛꜱ"
    set line 6 of lore of {_item} to "&8┃ &7ʜᴇᴀʟᴛʜ &8» &c+%{_health}%"
    set line 7 of lore of {_item} to "&8┃ &7ᴅᴇғᴇɴꜱᴇ &8» &a+%{_defense}%"
    
    set {_item} to unbreakable {_item}
    set item flags of {_item} to all item flags
    
    set text data tag "itemstat:type" of {_item} to "chestplate"
    set number data tag "itemstat:health" of {_item} to {_health}
    set number data tag "itemstat:defense" of {_item} to {_defense}
    
    return {_item}
        
function leggings(item: item, rarity: text, level: number):: item:
    set {_health} to round((8 + ({_level} * 1.5)) * 1.15)
    set {_defense} to round(8 + ({_level} * 1.2))
    
    set {_rarityline} to getRarityLine({_rarity})

    set line 1 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ɪɴғᴏ"
    set line 2 of lore of {_item} to "&8┃ &7ᴛʏᴘᴇ &8» &eʟᴇɢɢɪɴɢꜱ"
    set line 3 of lore of {_item} to "&8┃ &7ʀᴀʀɪᴛʏ &8» %{_rarityline}%"
    set line 4 of lore of {_item} to ""
    set line 5 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ꜱᴛᴀᴛꜱ"
    set line 6 of lore of {_item} to "&8┃ &7ʜᴇᴀʟᴛʜ &8» &c+%{_health}%"
    set line 7 of lore of {_item} to "&8┃ &7ᴅᴇғᴇɴꜱᴇ &8» &a+%{_defense}%"
    
    set {_item} to unbreakable {_item}
    set item flags of {_item} to all item flags
    
    set text data tag "itemstat:type" of {_item} to "leggings"
    set number data tag "itemstat:health" of {_item} to {_health}
    set number data tag "itemstat:defense" of {_item} to {_defense}
    
    return {_item}
        
function boots(item: item, rarity: text, level: number):: item:
    set {_health} to round((8 + ({_level} * 1.5)) * 1.15)
    set {_defense} to round(8 + ({_level} * 1.2))
    
    set {_rarityline} to getRarityLine({_rarity})

    set line 1 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ɪɴғᴏ"
    set line 2 of lore of {_item} to "&8┃ &7ᴛʏᴘᴇ &8» &eʙᴏᴏᴛꜱ"
    set line 3 of lore of {_item} to "&8┃ &7ʀᴀʀɪᴛʏ &8» %{_rarityline}%"
    set line 4 of lore of {_item} to ""
    set line 5 of lore of {_item} to "&8┃ &7» ɪᴛᴇᴍ ꜱᴛᴀᴛꜱ"
    set line 6 of lore of {_item} to "&8┃ &7ʜᴇᴀʟᴛʜ &8» &c+%{_health}%"
    set line 7 of lore of {_item} to "&8┃ &7ᴅᴇғᴇɴꜱᴇ &8» &a+%{_defense}%"
    
    set {_item} to unbreakable {_item}
    set item flags of {_item} to all item flags
    
    set text data tag "itemstat:type" of {_item} to "boots"
    set number data tag "itemstat:health" of {_item} to {_health}
    set number data tag "itemstat:defense" of {_item} to {_defense}
    
    return {_item}
    
command /modifyhelmet <text> <number>:
    permission: admin.item
    trigger:
        set {_item} to player's tool
        set player's tool to helmet({_item}, arg-1, arg-2)
    
command /modifychestplate <text> <number>:
    permission: admin.item
    trigger:
        set {_item} to player's tool
        set player's tool to chestplate({_item}, arg-1, arg-2)
    
command /modifyleggings <text> <number>:
    permission: admin.item
    trigger:
        set {_item} to player's tool
        set player's tool to leggings({_item}, arg-1, arg-2)
    
command /modifyboots <text> <number>:
    permission: admin.item
    trigger:
        set {_item} to player's tool
        set player's tool to boots({_item}, arg-1, arg-2)