command /createweapan <integer> <integer>:
    permission: op
    trigger:
        set {_type} to arg-1
        set {_material} to arg-2

        if {_type} = 1:
            set {_name} to "&fKatana"
            set {_speed} to 1.7
            set {_wood} to 2.5
            set {_stone} to 3
            set {_copper} to 3
            set {_iron} to 4
            set {_gold} to 2.5
            set {_diamond} to 5
            set {_netherite} to 6

        else if {_type} = 2:
            set {_name} to "&fKnife"
            set {_speed} to 3.0
            set {_wood} to 1
            set {_stone} to 1.5
            set {_copper} to 1.5
            set {_iron} to 2
            set {_gold} to 1
            set {_diamond} to 3
            set {_netherite} to 4

        else if {_type} = 3:
            set {_name} to "&fSaber"
            set {_speed} to 2.2
            set {_wood} to 3
            set {_stone} to 4
            set {_copper} to 4
            set {_iron} to 5
            set {_gold} to 3
            set {_diamond} to 6
            set {_netherite} to 7

        else if {_type} = 4:
            set {_name} to "&fLongsword"
            set {_speed} to 1.2
            set {_wood} to 4
            set {_stone} to 5
            set {_copper} to 5
            set {_iron} to 6
            set {_gold} to 4
            set {_diamond} to 7
            set {_netherite} to 8

        else if {_type} = 5:
            set {_name} to "&fRapier"
            set {_speed} to 1.9
            set {_wood} to 2
            set {_stone} to 2.5
            set {_copper} to 2.5
            set {_iron} to 3
            set {_gold} to 2
            set {_diamond} to 4
            set {_netherite} to 5

        else if {_type} = 6:
            set {_name} to "&fScythe"
            set {_speed} to 1.0
            set {_wood} to 6
            set {_stone} to 6.5
            set {_copper} to 6.5
            set {_iron} to 7
            set {_gold} to 6
            set {_diamond} to 8
            set {_netherite} to 9

        else:
            send "&cInvalid weapon type."
            stop

        if {_material} = 1:
            set {_item} to wooden sword
            set {_damage} to {_wood}
            set {_materialName} to "Wood"
        
        else if {_material} = 2:
            set {_item} to stone sword
            set {_damage} to {_stone}
            set {_materialName} to "Stone"
        
        else if {_material} = 3:
            set {_item} to copper sword
            set {_damage} to {_copper}
            set {_materialName} to "Copper"
        
        else if {_material} = 4:
            set {_item} to iron sword
            set {_damage} to {_iron}
            set {_materialName} to "Iron"
        
        else if {_material} = 5:
            set {_item} to golden sword
            set {_damage} to {_gold}
            set {_materialName} to "Gold"
        
        else if {_material} = 6:
            set {_item} to diamond sword
            set {_damage} to {_diamond}
            set {_materialName} to "Diamond"
        
        else if {_material} = 7:
            set {_item} to netherite sword
            set {_damage} to {_netherite}
            set {_materialName} to "Netherite"
        
        else:
            send "&cInvalid material."
            stop
        
        # NAME
        set name of {_item} to "%{_materialName}% %{_name}%"


        set {_damageModifier} to {_damage} - 1

        apply attribute modifier to {_item}:
            id: "minecraft:base_attack_damage"
            attribute: attack damage
            amount: {_damageModifier}
            slot: mainhand_slot_group
            operation: add_number


        set {_speedModifier} to {_speed} - 4

        apply attribute modifier to {_item}:
            id: "minecraft:base_attack_speed"
            attribute: attack speed
            amount: {_speedModifier}
            slot: mainhand_slot_group
            operation: add_number

        give player {_item}

        send "&aCreated %{_name}% &7(Material: %{_material}%)"