command /sethome:
    trigger:
        set {_loc::1} to x-coord of player's location
        set {_loc::2} to y-coord of player's location
        set {_loc::3} to z-coord of player's location
        set {_loc::4} to yaw of player's location
        set {_loc::5} to pitch of player's location
        send "&8[<##54ab7a>ʜᴏᴍᴇ&8]&7 ʏᴏᴜ ʜᴀᴠᴇ ꜱᴜᴄᴄᴇꜱꜱꜰᴜʟʟʏ ꜱᴇᴛ ᴀ ʜᴏᴍᴇ ʟᴏᴄᴀᴛɪᴏɴ."
        set number list data tag "home:loc" of player to {_loc::*}
        
command /home:
    trigger:
        set {_loc::*} to number list data tag "home:loc" of player
        if {_loc::1} is not set:
            send "&8[<##54ab7a>ʜᴏᴍᴇ&8]&c ʏᴏᴜ ʜᴀᴠᴇɴ'ᴛ ꜱᴇᴛ ᴀ ʜᴏᴍᴇ ʏᴇᴛ."
            stop trigger
        set {_home} to location({_loc::1}, {_loc::2}, {_loc::3}, player's world, {_loc::4}, {_loc::5})
        teleport player to {_home}
        send "&8[<##54ab7a>ʜᴏᴍᴇ&8]&7 ᴛᴇʟᴇᴘᴏʀᴛᴇᴅ ᴛᴏ ʏᴏᴜʀ ʜᴏᴍᴇ."
        
command /delhome [<player>]:
    trigger:
        if arg-1 is set:
            set {_p} to SmallCaps("%arg-1%")
            set {_check::*} to number list data tag "home:loc" of arg-1
            if {_check::*} is not set:
                send "&8[<##54ab7a>ʜᴏᴍᴇ&8]&e %{_p}% &cʜᴀꜱ ɴᴏ ʜᴏᴍᴇꜱ ꜱᴇᴛ."
                stop
            delete number list data tag "home:loc" of arg-1
            send "&8[<##54ab7a>ʜᴏᴍᴇ&8]&7 ʏᴏᴜ ʜᴀᴠᴇ ᴅᴇʟᴇᴛᴇᴅ&e %{_p}%&7'ꜱ ʜᴏᴍᴇ."
            stop
        set {_check::*} to number list data tag "home:loc" of player
        if {_check::*} is not set:
            send "&8[<##54ab7a>ʜᴏᴍᴇ&8]&c ʏᴏᴜ ʜᴀᴠᴇ ɴᴏ ʜᴏᴍᴇ ꜱᴇᴛ."
            stop
        delete number list data tag "home:loc" of player
        send "&8[<##54ab7a>ʜᴏᴍᴇ&8]&7 ʏᴏᴜ ʜᴀᴠᴇ ᴅᴇʟᴇᴛᴇᴅ ʏᴏᴜʀ ʜᴏᴍᴇ."