command /raceset <number>:
    permission: admin
    trigger:
        set number data tag "race:id" of player to arg-1
        
function raceName(p: player):: text:
    set {_race} to number data tag "race:id" of {_p}
    return switch return {_race}:
        case 1 -> "ʜᴜᴍᴀɴ"
        case 2 -> "ᴇʟꜰ"
        case 3 -> "ᴅᴡᴀʀꜰ"
        case 4 -> "ᴏʀᴄ"
        case 5 -> "ᴍᴇʀꜰʟᴏᴋ"
        case 6 -> "ᴠᴀᴍᴘɪʀᴇ"
        case 7 -> "ᴅᴇᴍᴏɴ"
        case 8 -> "ᴜɴᴅᴇᴀᴅ"
    
        
command /races:
    trigger:
        set {_name} to raceName(player)
        send "&7ʏᴏᴜʀ ʀᴀᴄᴇ ɪꜱ &e%{_name}%&7."