function syncRace(p: player):
    set {_race} to number data tag "race:id" of {_p}

    # Human
    if {_race} is 1:
        stop

    # Elf
    if {_race} is 2:
        stop

    # Dwarf
    if {_race} is 3:
        stop

    # Orc
    if {_race} is 4:
        stop

    # Merfolk
    if {_race} is 5:
        stop

    # Vampire
    if {_race} is 6:
        stop

    # Demon
    if {_race} is 7:
        stop

    # Undead
    if {_race} is 8:
        stop
        
every 5 ticks:
    loop all players:
        set {_race} to number data tag "race:id" of loop-player

        if {_race} is 2:
            apply night vision 1 to loop-player for 10 ticks:
                hide icon
                hide particles
            set max health of loop-player to 12.5
            apply speed 1 to loop-player for 10 ticks:
                hide icon
                hide particles
            if biome at loop-player is forest, birch forest, old growth birch forest, dark forest, flower forest, or pale garden:
                apply speed 2 to loop-player for 10 ticks:
                    hide icon
                    hide particles
                    
        if {_race} is 3:
            apply haste 1 to loop-player for 10 ticks:
                hide icon
                hide particles
            set scale attribute of loop-player to 0.5
            
on mine:
    if number data tag "race:id" of player is 3:
        if event-block is iron ore, gold ore, coal ore, diamond ore, emerald ore, lapis ore, redstone ore, nether quartz ore, nether gold ore or ancient debris:
            if player's tool is not enchanted with silk touch:
                drop drops of event-block at event-block's location
            