function getRaceByNumber(num: number) :: text:
    return switch return {_num}:
        case 1 -> "Werewolf"
        case 2 -> "Vampire"
        case 3 -> "Orc"
        case 4 -> "Dwarf"
        case 5 -> "Goblin"
        case 6 -> "Merfolk"
        case 7 -> "Elf"
        case 8 -> "Troll"
        case 9 -> "Kobold"
        case 10 -> "Gnome"
        case 11 -> "Kitsune"
        case 12 -> "Naga"
        case 13 -> "Oni"
        case 14 -> "Harpy"
        case 15 -> "Djinn"
        case 16 -> "Minotaur"
        case 17 -> "Yeti"
        case 18 -> "Dryad"
        case 19 -> "Phoenix"
        case 20 -> "Hydra"
        case 21 -> "Griffin"
        case 22 -> "Kraken"
        case 23 -> "Wendigo"
        case 24 -> "Angel"
        case 25 -> "Demon"
        case 26 -> "Devil"
        case 27 -> "Dragon"
        default -> "Unknown"

function getRaceRarity(num: number) :: text:
    return switch return {_num}:
        case 1, 2, 3, 4, 5, 6, 7, 8, 9 or 10 -> "common"
        case 11, 12, 13, 14, 15, 16, 17 or 18 -> "uncommon"
        case 19, 20, 21, 22 or 23 -> "rare"
        case 24, 25 or 26 -> "epic"
        case 27 -> "legendary"
        default -> "unknown"

command /race <number>:
    trigger:
        set {_race} to getRaceByNumber(arg-1)
        set {_rarity} to getRaceRarity(arg-1)
        send "The race corresponding to number %arg-1% is %{_race}% (%{_rarity}%)."