function fillRegion(x1: number, y1: number, z1: number, x2: number, y2: number, z2: number, block1: itemtype, block2: itemtype, chance: number):
    set {_minX} to min({_x1}, {_x2})
    set {_minY} to min({_y1}, {_y2})
    set {_minZ} to min({_z1}, {_z2})
    set {_maxX} to max({_x1}, {_x2})
    set {_maxY} to max({_y1}, {_y2})
    set {_maxZ} to max({_z1}, {_z2})
    set {_w} to world "world"

    loop integers from {_minX} to {_maxX}:
        loop integers from {_minY} to {_maxY}:
            loop integers from {_minZ} to {_maxZ}:
                set {_loc} to location(loop-value-1, loop-value-2, loop-value-3, {_w})
                if chance of {_chance}%:
                    set block at {_loc} to {_block1}
                else:
                    set block at {_loc} to {_block2}
        wait 1 tick


every 1 minute:
    if {reset.running} is true:
        stop
    set {reset.running} to true
    send action bar "&8[&4SYSTEM&8] &fAll mines have been reset!" to all players
    fillRegion(-48, 4, 6, -41, 9, 16, oak_planks, oak_log, 60)
    wait 5 ticks
    fillRegion(-34, 9, -7, -41, 4, -17,, stone, stone_bricks, 60)
    wait 5 ticks
    fillRegion(-19, 4, -24, -12, 9, -34, coal_ore, coal_block, 80)
    wait 5 ticks
    fillRegion(-6, 4, -46, 1, 9, -56, copper_ore, copper_block, 80)
    wait 5 ticks
    fillRegion(3, 4, -68, 10, 9, -78, iron_ore, iron_block, 80)
    wait 5 ticks
    fillRegion(23, 4, -87, 30, 9, -77, gold_ore, gold_block, 80)
    wait 5 ticks
    fillRegion(43, 4, -72, 50, 9, -62, deepslate_lapis_ore, lapis_block, 80)
    wait 5 ticks
    fillRegion(34, 4, -44, 41, 9, -34, deepslate_redstone_ore, redstone_block, 80)
    wait 5 ticks
    fillRegion(37, 4, -18, 44, 9, -8, deepslate_diamond_ore, diamond_block, 90)
    wait 5 ticks
    fillRegion(39, 4, 15, 32, 9, 25, deepslate_emerald_ore, emerald_block, 90)
    wait 5 ticks
    set {reset.running} to false

command /reset:
    permission: admin
    trigger:
        send action bar "&8[&4SYSTEM&8] &fAll mines have been reset!" to all players
        fillRegion(-48, 4, 6, -41, 9, 16, oak_planks, oak_log, 60)
        wait 5 ticks
        fillRegion(-34, 9, -7, -41, 4, -17,, stone, stone_bricks, 60)
        wait 5 ticks
        fillRegion(-19, 4, -24, -12, 9, -34, coal_ore, coal_block, 80)
        wait 5 ticks
        fillRegion(-6, 4, -46, 1, 9, -56, copper_ore, copper_block, 80)
        wait 5 ticks
        fillRegion(3, 4, -68, 10, 9, -78, iron_ore, iron_block, 80)
        wait 5 ticks
        fillRegion(23, 4, -87, 30, 9, -77, gold_ore, gold_block, 80)
        wait 5 ticks
        fillRegion(43, 4, -72, 50, 9, -62, deepslate_lapis_ore, lapis_block, 80)
        wait 5 ticks
        fillRegion(34, 4, -44, 41, 9, -34, deepslate_redstone_ore, redstone_block, 80)
        wait 5 ticks
        fillRegion(37, 4, -18, 44, 9, -8, deepslate_diamond_ore, diamond_block, 90)
        wait 5 ticks
        fillRegion(39, 4, 15, 32, 9, 25, deepslate_emerald_ore, emerald_block, 90)
        wait 5 ticks

command /togglereset:
    permission: admin
    trigger:
        if {reset.running} is true:
            set {reset.running} to false
            send action bar "&8[&4SYSTEM&8] &fMine regeneration has been &aenabled&f." to all players
        else:
            set {reset.running} to true
            send action bar "&8[&4SYSTEM&8] &fMine regeneration has been &cdisabled&f." to all players